-- Seed data for agent_metadata table

INSERT INTO agent_metadata (name, description, tools, input_schema, output_schema, recommended_ui_placement, trigger_options, instructions, model, reasoning_effort, verbosity, max_output_tokens) VALUES
('AI SDR Agent', 'Turn contacts into booked meetings using personalized outreach and follow-ups', '["ai-enrichment", "email-composer", "gmail-send-email", "communication-optimization", "sales-forecasting", "generate-demo-visuals"]', '{"contact_id": "string", "campaign_type": "string"}', '{"outreach_sequence": "array", "next_steps": "array", "images": "array"}', 'contact-toolbar', '{"manual": true, "auto": false}', 'You are an expert SDR assistant. Your goal is to turn contacts into booked meetings. Use personalized research, compelling messaging, and strategic timing to get responses and meetings booked. You can send emails directly via Gmail and schedule calendar events. Always provide specific, actionable outreach sequences with timing recommendations.', 'gpt-4o', 'medium', 'medium', 2000),
('AI Dialer Agent', 'Improve calls before, during, and after with AI-powered insights', '["ai-enrichment", "discovery-questions", "objection-handler", "voice-analysis", "summary-generator"]', '{"contact_id": "string", "call_type": "string"}', '{"call_brief": "object", "script": "string", "post_call_actions": "array"}', 'contact-toolbar', '{"manual": true}', 'You are a call optimization expert. Help sales reps prepare for, conduct, and follow up on calls. Provide call briefs, suggested scripts, objection handling, and post-call analysis with next steps.', 'gpt-4o', 'medium', 'medium', 1500),
('AI Journeys Agent', 'Create multi-step automations (email, social, tasks) for customer journeys', '["communication-optimizer", "lead-nurturing", "adaptive-playbook", "contact-analytics"]', '{"contact_id": "string", "journey_type": "string", "duration": "string"}', '{"journey_flow": "array", "tasks": "array", "automation_rules": "array"}', 'pipeline-buttons', '{"auto": true, "triggers": ["stage_change"]}', 'You are a customer journey orchestration expert. Design multi-step automated sequences that nurture leads through the sales process. Combine email, social, tasks, and follow-ups into cohesive customer experiences.', 'gpt-4o', 'high', 'medium', 2500),
('Signals Agent', 'Detect buying intent and risk signals in real-time', '["email-engagement-scoring", "journey-timeline", "deal-health-analysis", "sales-forecasting"]', '{"contact_id": "string", "deal_id": "string"}', '{"signals": "array", "alerts": "array", "risk_score": "number", "recommendations": "array"}', 'contact-toolbar', '{"auto": true, "interval": "daily"}', 'You are a sales signal detection expert. Monitor contacts and deals for buying intent signals, engagement patterns, and risk indicators. Provide real-time alerts and actionable recommendations to sales reps.', 'gpt-4o', 'high', 'low', 1000),
('Lead DB Agent', 'Continuous enrichment and hygiene for lead database', '["contact-enrichment", "ai-scoring", "relationship-mapping", "categorization", "territory-assignment", "vip-detection"]', '{"batch_size": "number", "enrichment_type": "string"}', '{"enriched_contacts": "array", "tags_added": "array", "data_quality_score": "number"}', 'pipeline-buttons', '{"auto": true, "interval": "weekly"}', 'You are a lead database optimization expert. Continuously enrich contact data, improve scoring accuracy, maintain data hygiene, and ensure proper categorization and territory assignment.', 'gpt-4o', 'medium', 'low', 1500),
('CRM Ops Agent', 'Clean, optimize, and structure CRM data and operations', '["semantic-search", "form-validation", "ai-insights", "automation-building"]', '{"operation_type": "string", "scope": "string"}', '{"cleaned_records": "array", "suggestions": "array", "automation_rules": "array"}', 'pipeline-buttons', '{"manual": true}', 'You are a CRM operations expert. Analyze CRM data quality, identify duplicates, suggest improvements, create automation rules, and optimize data structure for better sales performance.', 'gpt-4o', 'high', 'medium', 2000),
('Meetings Agent', 'Increase booked demos with strategic meeting scheduling', '["ai-scoring", "communication-optimizer", "email-composer", "gmail-send-email", "calendar-create-event", "social-message-generator"]', '{"contact_id": "string", "meeting_type": "string", "urgency": "string"}', '{"meeting_request_sequence": "array", "timing_recommendations": "array", "follow_up_plan": "array"}', 'contact-toolbar', '{"manual": true}', 'You are a meeting booking expert. Help sales reps get more meetings booked by optimizing outreach timing, personalization, and follow-up sequences. You can send emails via Gmail and create calendar events directly. Focus on strategic meeting requests that convert.', 'gpt-4o', 'medium', 'medium', 1500),
('AI AE Agent', 'Prepare and follow up on demos like a professional AE', '["feature-analysis", "market-trend-content", "deal-health-analysis", "sales-forecasting", "email-composer", "gmail-send-email", "calendar-create-event", "generate-demo-visuals"]', '{"deal_id": "string", "demo_type": "string", "generate_images": "boolean"}', '{"demo_agenda": "array", "recommended_slides": "array", "follow_up_sequence": "array", "images": "array"}', 'pipeline-buttons', '{"manual": true}', 'You are an expert Account Executive assistant. Help AEs prepare compelling demos, create professional follow-ups, analyze deal health, and generate supporting visuals. You can send emails via Gmail and schedule calendar events directly. Focus on value demonstration and next-step momentum.', 'gpt-4o', 'high', 'high', 3000),
('Agent Builder', 'Let users create custom agents with visual configuration', '["all-netlify-functions"]', '{"agent_name": "string", "description": "string", "tools": "array", "instructions": "string"}', '{"agent_config": "object", "validation_results": "object"}', 'pipeline-buttons', '{"manual": true}', 'You are an agent creation expert. Help users build custom AI agents by guiding them through configuration, tool selection, prompt crafting, and testing. Ensure agents are properly configured and validated.', 'gpt-4o', 'high', 'high', 2000),
('Voice Agent', 'Voice-first interaction for calls and audio analysis', '["speech-to-text", "voice-analysis", "summary-generation", "discovery-questions"]', '{"audio_file": "string", "call_type": "string"}', '{"transcription": "string", "sentiment": "object", "key_points": "array", "next_actions": "array"}', 'contact-toolbar', '{"manual": true}', 'You are a voice interaction expert. Process audio calls, provide transcriptions, analyze sentiment and tone, extract key insights, and suggest follow-up actions based on conversation analysis.', 'gpt-4o', 'medium', 'medium', 1500);
