export type AutopilotEvent =
  | "NEW_LEAD"
  | "OUTREACH_SENT"
  | "REPLY_RECEIVED"
  | "OBJECTION"
  | "INTEREST"
  | "MEETING_BOOKED"
  | "FOLLOWUP_REQUIRED"
  | "DEAL_WON"
  | "DEAL_LOST";

export const AUTOPILOT_EVENTS: Record<AutopilotEvent, AutopilotEvent> = {
  NEW_LEAD: "NEW_LEAD",
  OUTREACH_SENT: "OUTREACH_SENT",
  REPLY_RECEIVED: "REPLY_RECEIVED",
  OBJECTION: "OBJECTION",
  INTEREST: "INTEREST",
  MEETING_BOOKED: "MEETING_BOOKED",
  FOLLOWUP_REQUIRED: "FOLLOWUP_REQUIRED",
  DEAL_WON: "DEAL_WON",
  DEAL_LOST: "DEAL_LOST"
};
